// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cxovoevubqiwyqbvxfst.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN4b3ZvZXZ1YnFpd3lxYnZ4ZnN0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxNTcxMjQsImV4cCI6MjA2MjczMzEyNH0.lV8ymGrAduRytUU2Jp90npcbdp8R0Mcda-TlAGlB36E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);